name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable]

    steps:
    - uses: actions/checkout@v4

    - name: Install linux deps
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends just makepkg
      
    - name: Test this ver
      run: just test-this-ver
